// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN-_Gc_3ZUkDqW5-KWQ3yYpTBbZuM46zQ',
    appId: '1:698010481488:web:527979eae61369e6dd7255',
    messagingSenderId: '698010481488',
    projectId: 'dasi-project-7cfc6',
    authDomain: 'dasi-project-7cfc6.firebaseapp.com',
    storageBucket: 'dasi-project-7cfc6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgHQqZGfgW5g4A_6g1-KZvrn9FgvrZPug',
    appId: '1:698010481488:android:f482c7e00e0b81cddd7255',
    messagingSenderId: '698010481488',
    projectId: 'dasi-project-7cfc6',
    storageBucket: 'dasi-project-7cfc6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6XyQ1HDMcjHMZiqtkVgdmZRFQTo105-w',
    appId: '1:698010481488:ios:b46415e0aea9ef42dd7255',
    messagingSenderId: '698010481488',
    projectId: 'dasi-project-7cfc6',
    storageBucket: 'dasi-project-7cfc6.appspot.com',
    iosBundleId: 'com.example.refreshMateri',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6XyQ1HDMcjHMZiqtkVgdmZRFQTo105-w',
    appId: '1:698010481488:ios:b46415e0aea9ef42dd7255',
    messagingSenderId: '698010481488',
    projectId: 'dasi-project-7cfc6',
    storageBucket: 'dasi-project-7cfc6.appspot.com',
    iosBundleId: 'com.example.refreshMateri',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAN-_Gc_3ZUkDqW5-KWQ3yYpTBbZuM46zQ',
    appId: '1:698010481488:web:7d524f16e763afb7dd7255',
    messagingSenderId: '698010481488',
    projectId: 'dasi-project-7cfc6',
    authDomain: 'dasi-project-7cfc6.firebaseapp.com',
    storageBucket: 'dasi-project-7cfc6.appspot.com',
  );
}
